cluster:
  name: otlp-metrics-service-cluster

externalServices:
  prometheus:
    secret:
      create: false
      name: prometheus
      namespace: prometheus
    queryEndpoint: /api/v1/query
    writeEndpoint: /api/v1/otlp
    protocol: otlphttp
    tls:
      insecure_skip_verify: true
  loki:
    host: http://loki.loki.svc:3100
    tenantId: 1
    basicAuth:
      username: loki
      password: lokipassword
  tempo:
    host: http://tempo.tempo.svc:4318
    protocol: otlphttp
    tlsOptions: |-
      insecure             = true
      insecure_skip_verify = true

metrics:
  cost:
    enabled: false

logs:
  pod_logs:
    namespaces:
      - default
      - loki
      - prometheus
      - grafana
      - tempo
      - monitoring

traces:
  enabled: true

extraConfig: |-
  tracing {
    sampling_fraction = 0.1
    write_to = [otelcol.exporter.otlphttp.tempo.input]
  }

opencost:
  enabled: false

grafana-agent:
  agent:
    extraPorts:
      - name: "otlp-grpc"
        port: 4317
        targetPort: 4317
        protocol: "TCP"
      - name: "otlp-http"
        port: 4318
        targetPort: 4318
        protocol: "TCP"
      - name: "zipkin"
        port: 9411
        targetPort: 9411
        protocol: "TCP"
